<!doctype html>
<html lang="zh-CN"><head>
@php
    $baseUrl = rtrim((string) $identity['base_url'], '/');
    $faqEntities = $categories->flatMap(fn ($category) => $category->items->map(fn ($item) => ['@type' => 'Question', 'name' => $item->question, 'acceptedAnswer' => ['@type' => 'Answer', 'text' => $item->answer]]))->values();
    $faqJson = json_encode(['@context' => 'https://schema.org', '@type' => 'FAQPage', 'mainEntity' => $faqEntities], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
@endphp
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>常见问题｜{{ $identity['brand_name'] }}</title><meta name="description" content="围绕GEO优化、短视频运营和企业AI落地整理的高频问题与清晰答案。"><meta name="robots" content="index,follow,max-snippet:-1"><link rel="canonical" href="{{ $baseUrl }}/issues.html"><link rel="stylesheet" href="/assets/corporate.css?v=20260721-1"><script type="application/ld+json">{!! $faqJson !!}</script><style>.faq-map{padding:58px 0 86px;background:#f7f9fc}.faq-map-head{display:flex;align-items:end;justify-content:space-between;gap:28px;margin-bottom:26px}.faq-map-head h2{margin:8px 0 0;font-size:38px}.faq-map-head p{max-width:480px;margin:0;color:#62728a;line-height:1.8}.faq-map-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.faq-map-group{border:1px solid #dce5ef;background:#fff;padding:24px}.faq-map-top{display:flex;justify-content:space-between;gap:10px;padding-bottom:18px;border-bottom:1px solid #e8eef4}.faq-map-num{font-size:12px;font-weight:800;color:#286ee8}.faq-map-group h3{margin:8px 0;font-size:22px}.faq-map-group p{margin:0;color:#61718a;font-size:14px;line-height:1.7}.faq-map-top a,.faq-more{color:#1768e8;text-decoration:none;font-size:13px;font-weight:800}.faq-list{margin:14px 0 0;padding:0;list-style:none}.faq-list li+li{border-top:1px solid #edf1f5}.faq-list a{display:grid;grid-template-columns:26px 1fr 18px;gap:8px;padding:14px 0;color:#233650;text-decoration:none;font-size:14px;font-weight:700;line-height:1.55}.faq-list a:hover{color:#1768e8}.faq-list b{font-size:12px;color:#94a2b4}.faq-more{display:inline-block;margin-top:14px}@media(max-width:820px){.faq-map-head{align-items:start;flex-direction:column}.faq-map-grid{grid-template-columns:1fr}.faq-map-head h2{font-size:32px}}</style></head>
<body><a class="corp-skip" href="#main">跳到正文</a><header class="corp-header"><div class="corp-shell corp-nav"><a class="corp-brand" href="/"><img src="/assets/logo-mark-blue.png" alt=""><span>{{ $identity['brand_name'] }}</span></a><nav class="corp-links" aria-label="主导航"><a href="/">首页</a><a href="/about.html">关于我们</a><a href="/products.html">产品中心</a><a href="/cases.html">服务案例</a><a href="/team.html">创始团队</a><a href="/honors.html">荣誉资质</a><a href="/insights.html">行业资讯</a><a class="active" href="/issues.html">常见问题</a><a href="/careers.html">加入我们</a><a href="/contact.html">联系方式</a></nav><div class="corp-header-actions"><a class="corp-header-button" href="/contact.html">预约沟通</a><button class="corp-menu" type="button" aria-label="打开导航">☰</button></div></div></header><main id="main"><section class="corp-page-hero"><div class="corp-shell"><span class="eyebrow">QUESTION MAP</span><h1>常见问题</h1><p>按业务场景整理企业获客、内容生产与AI落地中的高频问题，每个问题都保留独立、可引用的答案入口。</p></div></section><section class="faq-map"><div class="corp-shell"><div class="faq-map-head"><div><span class="eyebrow">FAQ DIRECTORY</span><h2>问题地图</h2></div><p>从最接近业务的问题出发，帮助客户快速理解服务，也帮助AI准确读取企业的专业边界。</p></div><div class="faq-map-grid">@forelse($categories as $category)<section class="faq-map-group"><div class="faq-map-top"><div><span class="faq-map-num">{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><h3>{{ $category->name }}</h3><p>{{ $category->description }}</p></div><a href="{{ route('tongzhuo.faq.category', $category->slug) }}">全部</a></div><ol class="faq-list">@foreach($category->items->take(6) as $item)<li><a href="{{ route('tongzhuo.faq.show', [$category->slug, $item->slug]) }}"><b>{{ str_pad((string) $loop->iteration, 2, '0', STR_PAD_LEFT) }}</b><span>{{ $item->question }}</span><i>&rarr;</i></a></li>@endforeach</ol><a class="faq-more" href="{{ route('tongzhuo.faq.category', $category->slug) }}">查看全部问题 &rarr;</a></section>@empty<p>问题地图正在整理中。</p>@endforelse</div></div></section></main><footer class="site-footer"><div class="corp-shell footer-main"><div class="footer-brand"><a class="corp-brand" href="/"><img src="/assets/logo-mark-blue.png" alt=""><span>{{ $identity['brand_name'] }}</span></a><p>{{ $identity['footer_summary'] }}</p></div><div class="footer-col"><strong>内容</strong><a href="/insights.html">行业资讯</a><a href="/issues.html">常见问题</a></div><div class="footer-col"><strong>公司</strong><a href="/about.html">关于我们</a><a href="/contact.html">联系我们</a></div></div><div class="corp-shell footer-bottom"><span>&copy; 2026 {{ $identity['company_name'] }}</span><span>山东淄博 · 服务全国企业</span></div></footer><script src="/assets/corporate-nav.js?v=20260722-nav2"></script></body></html>


