<!doctype html>
<html lang="zh-CN">
<head>
@php $baseUrl = rtrim((string) ($identity['base_url'] ?? url('/')), '/'); @endphp
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $selectedCategory?->name ? $selectedCategory->name.'｜' : '' }}行业资讯｜{{ $identity['brand_name'] }}</title>
<meta name="description" content="桐灼科技持续发布GEO优化、短视频运营与企业AI落地的行业资讯和实操观点。"><meta name="robots" content="index,follow,max-snippet:-1"><link rel="canonical" href="{{ $canonicalUrl }}"><link rel="alternate" type="application/rss+xml" title="{{ $identity['brand_name'] }}行业资讯" href="{{ $baseUrl }}/feed.xml"><link rel="stylesheet" href="/assets/corporate.css?v=20260721-1">
<style>.content-page{padding:58px 0 86px;background:#f7f9fc}.content-page .corp-shell{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:34px}.insight-list{border-top:1px solid #cfd9e5}.insight-card{display:grid;grid-template-columns:102px minmax(0,1fr) 22px;gap:22px;align-items:center;padding:27px 0;border-bottom:1px solid #dfe7f0;color:#12233b;text-decoration:none}.insight-date{font-size:13px;font-weight:800;color:#2c70e8}.insight-date b{display:block;font-size:30px;line-height:1}.insight-meta{font-size:13px;font-weight:700;color:#2c70e8}.insight-card h2{margin:8px 0 8px;font-size:23px;line-height:1.35}.insight-card p{margin:0;color:#61718a;font-size:14px;line-height:1.75}.insight-arrow{font-size:22px;color:#2c70e8}.content-side{height:max-content;border:1px solid #d9e3ef;background:#fff;padding:20px}.content-side h2{margin:0 0 12px;font-size:16px}.content-side a{display:block;padding:11px 0;border-top:1px solid #edf1f5;color:#40516a;text-decoration:none;font-size:14px;font-weight:700}.content-side a.active,.content-side a:hover{color:#1768e8}.empty-state{padding:44px 0;color:#61718a}@media(max-width:820px){.content-page .corp-shell{grid-template-columns:1fr}.content-side{order:-1}.insight-card{grid-template-columns:74px minmax(0,1fr) 18px;gap:14px}.insight-card h2{font-size:19px}}</style>
</head>
<body>
<a class="corp-skip" href="#main">跳到正文</a><header class="corp-header"><div class="corp-shell corp-nav"><a class="corp-brand" href="/" aria-label="桐灼科技首页"><img src="/assets/logo-mark-blue.png" alt=""><span>{{ $identity['brand_name'] }}</span></a><nav class="corp-links" aria-label="主导航"><a href="/">首页</a><a href="/about.html">关于我们</a><a href="/products.html">产品中心</a><a href="/cases.html">服务案例</a><a href="/team.html">创始团队</a><a href="/honors.html">荣誉资质</a><a class="active" href="/insights.html">行业资讯</a><a href="/issues.html">常见问题</a><a href="/careers.html">加入我们</a><a href="/contact.html">联系方式</a></nav><div class="corp-header-actions"><a class="corp-header-button" href="/contact.html">预约沟通</a><button class="corp-menu" type="button" aria-label="打开导航" aria-expanded="false">☰</button></div></div></header>
<main id="main"><section class="corp-page-hero"><div class="corp-shell"><span class="eyebrow">KNOWLEDGE &amp; INSIGHTS</span><h1>{{ $selectedCategory?->name ?? '行业资讯' }}</h1><p>围绕GEO优化、短视频运营与企业AI落地，持续沉淀可被客户、搜索引擎和AI理解的专业内容。</p></div></section><section class="content-page"><div class="corp-shell"><div><div class="insight-list">@forelse($articles as $article)<a class="insight-card" href="/article/{{ $article->slug }}"><time class="insight-date" datetime="{{ optional($article->published_at)->toDateString() }}"><b>{{ optional($article->published_at)->format('d') }}</b>{{ optional($article->published_at)->format('Y.m') }}</time><div><div class="insight-meta">{{ $article->category?->name ?? '行业资讯' }}</div><h2>{{ $article->title }}</h2><p>{{ $summaries[$article->id] ?? $article->excerpt }}</p></div><span class="insight-arrow">&rarr;</span></a>@empty<div class="empty-state">暂时还没有已发布的文章。</div>@endforelse</div>{{ $articles->links() }}</div><aside class="content-side"><h2>资讯分类</h2><a class="{{ $selectedCategory ? '' : 'active' }}" href="/insights.html">全部文章</a>@foreach($categories as $category)<a class="{{ $selectedCategory?->id === $category->id ? 'active' : '' }}" href="/insights.html?category={{ $category->slug }}">{{ $category->name }}</a>@endforeach</aside></div></section></main>
<footer class="site-footer"><div class="corp-shell footer-main"><div class="footer-brand"><a class="corp-brand" href="/"><img src="/assets/logo-mark-blue.png" alt=""><span>{{ $identity['brand_name'] }}</span></a><p>{{ $identity['footer_summary'] ?? '桐灼（淄博）网络科技有限公司，专注GEO优化、短视频运营与企业AI落地。' }}</p></div><div class="footer-col"><strong>内容</strong><a href="/insights.html">行业资讯</a><a href="/issues.html">常见问题</a></div><div class="footer-col"><strong>公司</strong><a href="/about.html">关于我们</a><a href="/contact.html">联系我们</a></div></div><div class="corp-shell footer-bottom"><span>&copy; 2026 {{ $identity['company_name'] }}</span><span>山东淄博 · 服务全国企业</span></div></footer><script src="/assets/corporate-nav.js?v=20260722-nav2"></script>
</body></html>


