@extends('admin.layouts.app')

@section('content')
@php($settings = array_merge(['base_url' => '', 'footer_summary' => '', 'contact_phone' => '', 'contact_wechat' => '', 'address' => '', 'icp' => ''], $site->settings ?? []))
<div class="mx-auto max-w-[1200px] space-y-5">
    <div><div class="text-xs font-black tracking-[0.18em] text-violet-600">SITE IDENTITY</div><h1 class="mt-1 text-2xl font-black text-slate-950">全站设置</h1><p class="mt-1 text-sm text-slate-500">统一管理公司实体、公开域名、联系方式和AI抓取基础信息。</p></div>
    <form method="POST" action="{{ route('admin.tongzhuo-cms.settings.save') }}" class="space-y-5">
        @csrf
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="border-b border-slate-100 pb-4"><h2 class="font-black text-slate-950">品牌与公开地址</h2><p class="mt-1 text-sm text-slate-500">正式上线后请将公开域名改为HTTPS域名，不要继续使用IP和端口作为Canonical。</p></div><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="text-sm font-bold text-slate-700">公司全称<input name="name" required value="{{ old('name', $site->name) }}" class="mt-2 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-sm font-bold text-slate-700">品牌名称<input name="brand_name" required value="{{ old('brand_name', $site->brand_name) }}" class="mt-2 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-sm font-bold text-slate-700">域名<input name="domain" value="{{ old('domain', $site->domain) }}" placeholder="www.example.com" class="mt-2 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-sm font-bold text-slate-700">公开基础网址<input name="settings[base_url]" type="url" value="{{ old('settings.base_url', $settings['base_url']) }}" placeholder="https://www.example.com" class="mt-2 block w-full rounded-lg border-slate-200 text-sm"></label></div></section>
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="border-b border-slate-100 pb-4"><h2 class="font-black text-slate-950">联系信息</h2><p class="mt-1 text-sm text-slate-500">官网表单、AI说明文件、RSS和页面结构化信息会共用这些基础资料。</p></div><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="text-sm font-bold text-slate-700">联系电话<input name="settings[contact_phone]" value="{{ old('settings.contact_phone', $settings['contact_phone']) }}" class="mt-2 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-sm font-bold text-slate-700">商务微信<input name="settings[contact_wechat]" value="{{ old('settings.contact_wechat', $settings['contact_wechat']) }}" class="mt-2 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-sm font-bold text-slate-700 md:col-span-2">联系地址<input name="settings[address]" value="{{ old('settings.address', $settings['address']) }}" class="mt-2 block w-full rounded-lg border-slate-200 text-sm"></label><label class="text-sm font-bold text-slate-700 md:col-span-2">页脚简介<textarea name="settings[footer_summary]" rows="3" class="mt-2 block w-full rounded-lg border-slate-200 text-sm">{{ old('settings.footer_summary', $settings['footer_summary']) }}</textarea></label><label class="text-sm font-bold text-slate-700">ICP备案号<input name="settings[icp]" value="{{ old('settings.icp', $settings['icp']) }}" class="mt-2 block w-full rounded-lg border-slate-200 text-sm"></label></div></section>
        <div class="flex justify-end"><button class="rounded-lg bg-slate-950 px-5 py-2.5 text-sm font-bold text-white hover:bg-blue-700">保存全站设置</button></div>
    </form>
</div>
@endsection
