@extends('admin.layouts.app')

@section('content')
<div class="mx-auto max-w-[1600px] space-y-5">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><a href="{{ route('admin.geo-growth.index') }}" class="text-sm font-bold text-blue-600 hover:underline">← 返回GEO增长</a><h1 class="mt-2 text-2xl font-black text-slate-950">网站诊断报告</h1><p class="mt-1 break-all text-sm text-slate-500">{{ $audit->url }}</p></div><span class="rounded-full px-3 py-1.5 text-sm font-black {{ $audit->score >= 80 ? 'bg-emerald-50 text-emerald-700' : ($audit->score >= 60 ? 'bg-amber-50 text-amber-700' : 'bg-red-50 text-red-700') }}">基础可读性得分 {{ $audit->score ?? '--' }}/100</span></div>
    @if($audit->status === 'failed')<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">诊断失败：{{ $audit->error_message }}</div>@endif
    <section class="grid gap-4 sm:grid-cols-4"><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="text-sm text-slate-500">发现总数</div><div class="mt-2 text-3xl font-black text-slate-950">{{ $audit->summary['total'] ?? $audit->findings->count() }}</div></div><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="text-sm text-slate-500">严重问题</div><div class="mt-2 text-3xl font-black text-red-600">{{ $audit->summary['critical'] ?? 0 }}</div></div><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="text-sm text-slate-500">需要优化</div><div class="mt-2 text-3xl font-black text-amber-600">{{ $audit->summary['warning'] ?? 0 }}</div></div><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="text-sm text-slate-500">自动任务</div><div class="mt-2 text-3xl font-black text-blue-600">{{ $audit->tasks->count() }}</div></div></section>
    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-black text-slate-950">诊断发现</h2><p class="mt-1 text-sm text-slate-500">这是网站基础结构检查结果；接入GEORank引擎后，会继续增加AI问答可见性、实体和引用信号分析。</p></div><div class="divide-y divide-slate-100">@forelse($audit->findings as $finding)<article class="px-5 py-5"><div class="flex items-start gap-3"><span class="mt-0.5 rounded-full px-2.5 py-1 text-xs font-black {{ $finding->severity === 'critical' ? 'bg-red-50 text-red-700' : ($finding->severity === 'warning' ? 'bg-amber-50 text-amber-700' : 'bg-blue-50 text-blue-700') }}">{{ $finding->severity === 'critical' ? '严重' : ($finding->severity === 'warning' ? '优化' : '建议') }}</span><div class="min-w-0 flex-1"><h3 class="font-black text-slate-950">{{ $finding->title }}</h3><p class="mt-2 text-sm leading-6 text-slate-600">{{ $finding->description }}</p><p class="mt-2 text-sm font-bold leading-6 text-slate-800">建议：{{ $finding->suggestion }}</p></div></div></article>@empty<div class="px-5 py-12 text-center text-sm text-emerald-700">暂未发现问题，继续完善内容资产和AI问答覆盖。</div>@endforelse</div></section>
</div>
@endsection
